name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    # Repository-Code auschecken
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up QEMU für Multiarch
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    # Set up Docker Buildx für Multiarch
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Baue das Docker-Image und extrahiere die Version
    - name: Build Docker Image
      id: build_image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/rtl_tcp:latest .
        version=$(docker run --rm ghcr.io/${{ github.repository_owner }}/rtl_tcp:latest cat /version.txt)
        echo "Image version: $version"
        echo "version=$version" >> $GITHUB_ENV

    # Pushe das Docker-Image mit Tag
    - name: Push Docker Image with Version Tag
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/rtl_tcp:latest
          ghcr.io/${{ github.repository_owner }}/rtl_tcp:${{ env.version }}
        platforms: linux/amd64,linux/arm64,linux/arm/v7
